name: 12 on stretch-slim

on:
  pull_request:
    paths:
      - 12/stretch-slim/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install bats
      - run: ./test-build.sh $NODE_VERSION $VARIANT
    env:
      NODE_VERSION: "12"
      VARIANT: "stretch-slim"
