name: 13 on stretch-slim

on:
  pull_request:
    paths:
      - 13/stretch-slim/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install bats
      - run: ./test-build.sh $NODE_VERSION $VARIANT
    env:
      NODE_VERSION: "13"
      VARIANT: "stretch-slim"
