name: PR to official images

on:
  push:
    # branches:
    #   - master
    paths:
      - "**/Dockerfile"
      - "**/docker-entrypoint.sh"
      - "generate-stackbrew-*.sh"
      - ".github/workflows/official-images.yml"

jobs:
  pr:
    runs-on: ubuntu-latest
    # if: github.repository_owner == 'nodejs'

    steps:
      - name: Checkout the docker-node repo
        uses: actions/checkout@v2
        with:
          folder: docker-node

      - name: Checkout the official-images repo
        uses: actions/checkout@v2
        with:
          folder: official-images
          repository: docker-library/official-images

      - name: Generate Stackbrew for diff
        run: ./docker-node/generate-stackbrew-library.sh >> official-images/library/node

      - name: Check for diff
        run: |
          cd official-images
          git diff --exit-code
