name: Check Shell scripts

on:
  pull_request:
    paths:
      - "**/*.sh"

jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.1.0
