name: Check Shell scripts

on:
  pull_request:
    paths:
      - "**/*.sh"

permissions:
  contents: read

jobs:
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: docker run -v "$(pwd)":/sh -w /sh peterdavehello/shfmt:2.6.3 shfmt -sr -i 2 -l -w -ci .
      - run: git diff --color --exit-code

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: shellcheck *.sh
